#!/bin/bash

node accident_a1.js > accident_a1.svg
node svg_to_png.js accident_a1

node accident_a2.js > accident_a2.svg
node svg_to_png.js accident_a2

node accident_a3.js > accident_a3.svg
node svg_to_png.js accident_a3

node accident_case_a1.js > accident_case_a1.svg
node svg_to_png.js accident_case_a1

node accident_case_a2.js > accident_case_a2.svg
node svg_to_png.js accident_case_a2

node accident_case_a3.js > accident_case_a3.svg
node svg_to_png.js accident_case_a3

node speech_pattern.js > speech_pattern.svg
node svg_to_png.js speech_pattern

node tips_idea_1.js > tips_idea_1.svg
node svg_to_png.js tips_idea_1

git add .
git commit -am "Quick save..."
git push

cp ./accident_a1.svg /Volumes/TriveStorage/diagrams/accident/images/accident_a1.svg
cp ./accident_a1.png /Volumes/TriveStorage/diagrams/accident/images/accident_a1.png

cp ./accident_a2.svg /Volumes/TriveStorage/diagrams/accident/images/accident_a2.svg
cp ./accident_a2.png /Volumes/TriveStorage/diagrams/accident/images/accident_a2.png

cp ./accident_a3.svg /Volumes/TriveStorage/diagrams/accident/images/accident_a3.svg
cp ./accident_a3.png /Volumes/TriveStorage/diagrams/accident/images/accident_a3.png

cp ./accident_case_a1.svg /Volumes/TriveStorage/diagrams/accident/images/accident_case_a1.svg
cp ./accident_case_a1.png /Volumes/TriveStorage/diagrams/accident/images/accident_case_a1.png

cp ./accident_case_a2.svg /Volumes/TriveStorage/diagrams/accident/images/accident_case_a2.svg
cp ./accident_case_a2.png /Volumes/TriveStorage/diagrams/accident/images/accident_case_a2.png

cp ./accident_case_a3.svg /Volumes/TriveStorage/diagrams/accident/images/accident_case_a3.svg
cp ./accident_case_a3.png /Volumes/TriveStorage/diagrams/accident/images/accident_case_a3.png

cp ./speech_pattern.svg /Volumes/TriveStorage/diagrams/accident/images/speech_pattern.svg
cp ./speech_pattern.png /Volumes/TriveStorage/diagrams/accident/images/speech_pattern.png

cp ./tips_idea_1.svg /Volumes/TriveStorage/diagrams/accident/images/tips_idea_1.svg
cp ./tips_idea_1.png /Volumes/TriveStorage/diagrams/accident/images/tips_idea_1.png

cd /Volumes/TriveStorage/diagrams/accident
git add .
git commit -am "Quick save..."
git push