#!/bin/bash

echo "Generating the database diagram svg..."
node diagram_db.js > diagram_db.svg
echo "Generating the database diagram png..."
node svg_to_png.js diagram_db

git add .
git commit -am "Quick save..."
git push
cp ./diagram_db.svg /Users/jo/go/src/github.com/chousemath/myfuncoo/diagram_db.svg